from __future__ import annotations

from abc import ABC, abstractmethod


class BaseRuntime(ABC):

    @abstractmethod
    async def invoke(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Invoke an LLM and return the generated text.

        Returns:
            Raw text generated by the model.
        """
        ...